name: OCI Function Continuous Integration with Approval

on:
  workflow_dispatch:  # Enables manual execution from the GitHub UI
    inputs:
      environment:
        description: 'The environment to deploy to (e.g., dev, prod)'
        required: true
        default: 'dev'
      dry-run:
        description: 'Enable or disable dry-run mode'
        required: false
        default: 'false'
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - develop

permissions:  # Ajouter cette section pour configurer les permissions globales
  id-token: write
  contents: read

jobs:
  python-workflow:
    uses: soltani-a/soltania-devops-github-actions-templates-prototype/.github/workflows/python-ci-template.yml@main
    secrets: inherit
    with:
      python-versions: '3.12' 
      source-directory: 'src/main/python'
      test-directory: 'src/test/python'

  terraform-workflow:
    uses: soltani-a/soltania-devops-github-actions-templates-prototype/.github/workflows/terraform-ci-template.yml@main
    secrets: inherit
    needs: python-workflow
    with:
      terraform-directory: 'src/main/terraform'
      oci-region: "${{ vars.OCI_REGION }}"
      aws-s3-endpoint-url: "${{ vars.AWS_S3_ENDPOINT_URL }}"
      aws-s3-bucket-name: "${{ vars.AWS_S3_BUCKET_NAME }}"
      aws-s3-region: "${{ vars.AWS_REGION }}"